trigger:
  branches:
    include:
    - main

pool:
  vmImage: ubuntu-latest

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.9'
    addToPath: true

- script: |
    python -m pip install --upgrade pip
    pip install -U pytest
    pip install beautifultable
    pip install -r requirements.txt
  displayName: 'Install dependencies'

- script: |
    cd test
    pytest --junitxml=unittest.xml
  displayName: 'Run unit tests'
