trigger:
  branches:
    include:
      - main
  pr:
    - main:
        branches:
          include:
            - '*'
        # Only run the pipeline when the pull request is manually completed
        # and all required reviews have been approved
        # and the pull request does not have any merge conflicts
        # and the pull request has passed any required status checks
        # and the pull request is not a draft
        trigger: manual

pool:
  vmImage: ubuntu-latest

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.9'
      addToPath: true

  - script: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
      pip install pytest
    displayName: 'Install dependencies'

  - script: |
      cd test
      pytest  --junitxml=unittest.xml
    displayName: 'Run unit tests'

  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: '**/unittest.xml'
      testRunTitle: 'Unit Tests'
    displayName: 'Publish test results'
