trigger:
  branches:
    include:
      - main
  # Manual trigger for pull requests
  # Pull requests must be explicitly run by a user
  pr:
    - main:
        branches:
          include:
            - '*'
        # Only run the pipeline when a pull request is manually completed
        trigger: manual
pool:
  vmImage: ubuntu-latest

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.9'
      addToPath: true

  - script: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
      pip install pytest
    displayName: 'Install dependencies'

  - script: |
      cd test
      pytest  --junitxml=unittest.xml
    displayName: 'Run unit tests'

  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: '**/unittest.xml'
      testRunTitle: 'Unit Tests'
    displayName: 'Publish test results'
