trigger: none 
pr:
  branches:
    include:
    - main
pool:
  vmImage: ubuntu-latest

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.9'
      addToPath: true

  - script: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
      pip install pytest
    displayName: 'Install dependencies'

  - script: |
      cd test
      pytest  --junitxml=unittest.xml
    displayName: 'Run unit tests'

  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: '**/unittest.xml'
      testRunTitle: 'Unit Tests'
    displayName: 'Publish test results'
